# @package _global_

task:
  name: finetune_mean
  aggregation: mean
  bag_key: region_id
  bag_fallback_key: sample_id
  max_instances_per_bag: 0
  instance_sampling: all
  target_type: binary
  target_columns: null
  loss: categorical_bce
