# @package _global_

defaults:
  - _self_
  - data: spatial_omics # choose datamodule with `test_dataloader()` for evaluation
  - task: finetune_mean
  - model: supervised_module
  - optim: adamw
  - scheduler: cosine_epoch
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
